from .admin import dp
from .ai import dp
from .arrest import dp
from .blowup import dp
from .bury import dp
from .castrate import dp
from .chopoff import dp
from .destroy import dp
from .digout import dp
from .drink import dp
from .duel import dp
from .dungeon import dp
from .flogged import dp
from .force import dp
from .fuck import dp
from .guess import dp
from .hangup import dp
from .help import dp
from .humiliate import dp
from .laugh import dp
from .offer import dp
from .punish import dp
from .reg import dp
from .rps import dp
from .sell import dp
from .send import dp
from .shootoff import dp
from .stagger import dp
from .suck import dp
from .swear import dp
from .tear import dp
from .tickle import dp
from .tie import dp
from .wish import dp
from .xo import dp
from .xoo import dp
from .yell import dp

__all__ = ["dp"]